@startuml

title Extensible GenAI Service Schemas Diagram

entity ChatActor {
    id: UUID
    * type: String
}

entity ChatIntentionHandler {
    func: ServerlessFunc
    context: ChatSession
    prompt: String
}

entity ChatMessage {
    * id: UUID
    * sender: ChatActor
    receiver: ChatActor
    * msg: String
    * session_id: UUID
}

entity ChatModule {
    * id: UUID
    * name: String
    * description: String
    * initial_context: JSONSchema
    * intention_handlers: List<ChatIntentionHandler>
    view_handler: List<ChatViewHandler>
    * agent_prompt: String
}

entity ChatSession {
    * id: UUID
    * initial_context: Object
    created_at: Date
    updated_at: Date
    status: SessionStatus
    * module_id: UUID
    message_ids: List<UUID>
}

entity ChatViewHandler {
    client_type: String
    message_constructor: ServerlessFunc
    action_handlers: List<ServerlessFunc>
}

entity Document {
    metadata: DocumentMetadata
    data: DocumentData
}

entity DocumentData {
}

entity DocumentMetadata {
    name: String
    type: String
    tags: List<String>
    module_id: UUID
}

entity JSONSchema {
    schema: String
}

entity KVPair {
    * key: String
    * value: Object
}

entity ServerlessFunc {
    * description: String
    * id: UUID
    * name: String
    * source: String
    * interface_schema: ServerlessFuncInterfaceSchema
}

entity ServerlessFuncInterfaceSchema {
    * input_params: JSONSchema
    * returns: JSONSchema
}

entity SessionStatus {
    * id: UUID
    * state: String
    details: KVPair
}

entity EmbeddingsDataGenerator {
    func: ServerlessFunc
}


ChatViewHandler -- ServerlessFunc : message_constructor
ChatViewHandler -- "0..*" ServerlessFunc : action_handlers
ChatMessage -- ChatActor : sender
ChatMessage -- ChatActor : receiver
ServerlessFuncInterfaceSchema -- JSONSchema : input_params
ServerlessFuncInterfaceSchema -- JSONSchema : returns
Document -- DocumentData : data
Document -- DocumentMetadata: metadata
ChatSession -- SessionStatus : status
ChatSession -- "0..*" ChatMessage : messages
SessionStatus -- KVPair : details
ServerlessFunc -- ServerlessFuncInterfaceSchema : interface_schema
EmbeddingsDataGenerator -- ServerlessFunc : func
EmbeddingsDataGenerator -- "0..*" Document
ChatIntentionHandler -- ServerlessFunc : func
ChatIntentionHandler -- ChatSession : context
ChatModule -- JSONSchema : initial_context
ChatModule -- "0..*" ChatIntentionHandler : intention_handlers
ChatModule -- ChatViewHandler : view_handler
ChatModule -- EmbeddingsDataGenerator: embeddings_provider

@enduml